### ISSUE TITLE
node v4.2.2  breaks #15, #25, fix broken inlining of regular expressions containing slashes

### ISSUE THREAD

**Issue by alockwood05** [bugventure/jsen#47]
1 failing

  1) fixes Fix broken inlining of regular expressions containing slashes (#15, #25):
     SyntaxError: Invalid regular expression flags
      at Function (native)
      at Function.builder.compile (/Users/alexanderlockwood/git/jsen/lib/func.js:58:25)
      at compile (/Users/alexanderlockwood/git/jsen/lib/jsen.js:908:25)
      at jsen (/Users/alexanderlockwood/git/jsen/lib/jsen.js:923:12)
      at /Users/alexanderlockwood/git/jsen/test/fixes.js:14:13
      at Function._throws (assert.js:297:5)
      at Function.assert.doesNotThrow (assert.js:328:11)
      at Context.<anonymous> (/Users/alexanderlockwood/git/jsen/test/fixes.js:13:16)
      at callFn (/Users/alexanderlockwood/git/jsen/node_modules/mocha/lib/runnable.js:250:21)
      at Test.Runnable.run (/Users/alexanderlockwood/git/jsen/node_modules/mocha/lib/runnable.js:243:7)
      at Runner.runTest (/Users/alexanderlockwood/git/jsen/node_modules/mocha/lib/runner.js:373:10)
      at /Users/alexanderlockwood/git/jsen/node_modules/mocha/lib/runner.js:451:12
      at next (/Users/alexanderlockwood/git/jsen/node_modules/mocha/lib/runner.js:298:14)
      at /Users/alexanderlockwood/git/jsen/node_modules/mocha/lib/runner.js:308:7
      at next (/Users/alexanderlockwood/git/jsen/node_modules/mocha/lib/runner.js:246:23)
      at Immediate._onImmediate (/Users/alexanderlockwood/git/jsen/node_modules/mocha/lib/runner.js:275:5)
      at processImmediate [as _immediateCallback] (timers.js:383:17)

**Comment by bugventure** [comment]
Thank you for reporting the issue. Travis CI now reports passing tests with versions of node from v0.10 up to v5.
